package week2;

import java.math.BigInteger;
import java.util.ArrayList;

//Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
//
//22=4, 23=8, 24=16, 25=32
//32=9, 33=27, 34=81, 35=243
//42=16, 43=64, 44=256, 45=1024
//52=25, 53=125, 54=625, 55=3125
//If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
//
//4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
//
//How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
//

public class IntegerCombinations 
{
	
	public static int count()
	{
		ArrayList<BigInteger> find = new ArrayList<BigInteger>();
		BigInteger temp;
		for (int a = 2; a <= 100; a++) 
		{
			for (int b = 2; b <= 100; b++) 
			{
				temp=BigInteger.valueOf(a).pow(b);
				if (!find.contains(temp)) 
				{
					find.add(temp);
				}
			}
		}
		System.out.println(find);
		System.out.println(find.size());
		return 0;
	}	
	
	public static void main(String[] args)
	{

		IntegerCombinations.count();

	}
}
