package week3;

/*Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.*/

import week3.Pentagonal; //Importing Method from my previous Program

public class PentaTriHexa {

	public static void main(String[] args) 
	{
		long result = 0;
        int i = 143;

        while (true) 
        {
            i++;
            result = i * (2 * i - 1); //Formula for both Triangular & Hexagonal Numbers.

            if (Pentagonal.isPentagonal(result)) 
            {
                break;
            }                    
        }
		System.out.println("Next triangle number that is also pentagonal and hexagonal is:" +result);
	}

}
